caikit/caikit-nlp

pyproject.toml
Needs 19.0 or greater to install alongside current versions of caikit
=> Update pyproject.toml accelerators version

pyproject.toml
- Bump `caikit` for bidirectional streaming support - https://github.com/caikit/caikit/releases/tag/v0.10.0 and https://github.com/caikit/caikit/releases/tag/v0.10.1
- Bump `caikit-tgis-backend` with corresponding version range updates (no functional changes here) - https://github.com/caikit/caikit-tgis-backend/releases/tag/v0.1.8
Closes #68
=> :arrow_up: Bump caikit and caikit-tgis-backend

caikit_nlp/modules/text_generation/fine_tuning.py, examples/run_fine_tuning.py, examples/utils.py, pyproject.toml, tests/modules/text_generation/test_fine_tuning.py
Closes: #75 
- Update transformers to latest version that enables bugfix for Trainer prediction
- Add [samsum](https://huggingface.co/datasets/samsum) and [billsum](https://huggingface.co/datasets/billsum) dataset from huggingface to test out summarization
- Change default input text length to support summarization
- Fix prediction generation batch decoding to single output mapping issue
- Add evaluation in fine-tuning notebook
1. Unit test: `tox -e py39 -- tests`
2. Evaluation example:
```python
ALLOW_DOWNLOADS=true python3 run_fine_tuning.py --dataset "billsum"  --model_name t5-base --num_epochs 4 --output_dir tmp/with_loss_log --batch_size=8 --accumulate_steps 16 --max_source_length 1024 --metric rouge --torch_dtype float16
```
=> Add eval fine tuning

caikit_nlp/modules/text_generation/peft_prompt_tuning.py
- Currently `Autoconfig` is by default going off of HF hub and fetching model configurations, which may not always be required depending on the usecase and may create confusion if the model version changed on HF Hub. This PR makes this configurable with the `ALLOW_DOWNLOADS` flag
=> :bug: Fix autoconfig always fetching info from model-hub

caikit_nlp/modules/text_generation/peft_tgis_remote.py, caikit_nlp/modules/text_generation/text_generation.py, caikit_nlp/toolkit/tgis_utils.py, runtime_config.yaml, scripts/run_local.sh, tests/fixtures/__init__.py, tests/modules/text_generation/test_peft_tgis_remote.py, tests/modules/text_generation/test_text_generation.py, tox.ini
This PR makes updates to `peft_tgis_remote` and `text_generation`, the two `text_generation` module implementations that use a `TGISBackend`, to make them work with remote TGIS connections and no local artifacts. The changes include:
* Updating the `save/load` logic in `TextGeneration` to support saving and loading without artifacts
* Update the `save/load` logic in `TextGeneration` to preserve the base model name
* Update `PeftPromptTuningTGIS` to call the backend's `load_prompt_artifacts` to get the artifacts "loaded" to TGIS. In practice, this just means copying them to a preconfigured "prompt_dir" that the `TGISBackend` is assuming is a shared volume mount with TGIS for the prompt cache.
Aside from unit tests, I've tested this out with a locally running server and port-forwards to …
=> Remote tgis text gen

caikit_nlp/model_management/__init__.py, caikit_nlp/model_management/tgis_auto_finder.py, caikit_nlp/modules/text_generation/text_generation_tgis.py, pyproject.toml, runtime_config.yaml, tests/conftest.py, tests/fixtures/__init__.py, tests/model_management/test_tgis_auto_finder.py, tests/modules/text_generation/test_text_generation_local.py, tests/modules/text_generation/test_text_generation_tgis.py
This PR introduces the `TGISAutoFinder` which implements the `ModelFinderBase` interface. When configured in `model_management.finders`, this allows `caikit.load` (and by extension `caikit.runtime` model loading) to automatically find models that are managed by TGIS for the `text-generation` task without needing those models to exist on-disk with a `config.yml` file.
```sh
k port-forward svc/bloom-560m-inference-server 8033
```
```py
import caikit
from caikit_nlp.model_management import TGISAutoFinder
caikit.configure(
config_dict={
"model_management": {
"finders": {
"default": {
"type": TGISAutoFinder.name,
"config": {},
}
},
"initializers": {
"default": {
"type": "LOCAL",
"config": {
"backend_priority": [
{
"type": "TGIS",
"config": {
"connection": {
"hostname": "localhost:8033",
}
}
} …
```
=> Tgis auto finder

caikit_nlp/modules/text_generation/text_generation_local.py
closes: #121 
- Fix training function argument to fix warnings and errors in caikit service generation.
=> :bug: Fix training arguments for service generation to work correctly

examples/run_fine_tuning.py
fixed simple typo in run_fine_tuning.py
=> fixed simple typo in run_fine_tuning.py

examples/run_fine_tuning.py
- update fine-tuning example script to allow saving of the model by default (without tgis)
- pass on `args.max_target_length` as `max_new_tokens` to run functions, to allow easier evaluation
=> Update fine-tuning example to allow local save of the model and flexible target seq len

CODEOWNERS
- Adding Gabe as codeowner to help update to this repo in absence of maintainers
=> Welcome back Gabe

examples/run_fine_tuning.py
Simple bugfix to pass the Caikit NLP CLI `--dtype` argument to bootstrapping, allowing half precision models to be loaded `.from_pretrained()`
=> Closes #134

caikit_nlp/modules/text_generation/peft_prompt_tuning.py, pyproject.toml
- Remove wip tag from prompt tuning module for streaming function which causes the API generation to fail
=> Fix stream api gen

pyproject.toml
- MPT peft PR got merged to peft main repo last night and branch on mayank's repo got deleted. This broke caikit-nlp build. To get it working again, for now we are peft+mpt from main branch of peft repo since latest version hasn't released yet.
=> :adhesive_bandage::package: Fix peft installation

caikit_nlp/data_model/generation.py, tests/data_model/test_generation.py
Supports #140 
Adding `ExponentialDecayLengthPenalty` data model to capture text generation input inference parameters related to length penalty.
=> ✨ ExponentialDecayLengthPenalty data model

caikit_nlp/modules/text_generation/peft_prompt_tuning.py, caikit_nlp/modules/text_generation/text_generation_local.py, caikit_nlp/toolkit/text_generation/model_run_utils.py, pyproject.toml, tests/modules/text_generation/test_peft_prompt_tuning.py
=> Flattened inf params

caikit_nlp/toolkit/text_generation/model_run_utils.py, caikit_nlp/toolkit/text_generation/tgis_utils.py
Allowing `eos_token` to be `None`
=> eos_token bug fix

caikit_nlp/modules/text_generation/peft_prompt_tuning.py, caikit_nlp/modules/text_generation/peft_tgis_remote.py, caikit_nlp/modules/text_generation/text_generation_tgis.py, caikit_nlp/toolkit/text_generation/model_run_utils.py
=> Fix seed type mismatch

caikit_nlp/modules/text_generation/peft_prompt_tuning.py
- Change `lr` to `learning_rate` to make it more intuitive 
- Mark training parameter with default as optional via type annotation for the correct runtime service generation.
=> :truck: Change parameter name and mark them optional for runtime

caikit_nlp/toolkit/text_generation/model_run_utils.py, tests/modules/text_generation/test_peft_prompt_tuning.py
- For causal-lm models we need attention mask to be able to run generate function
- `task_ids` is now a compulsory field in PEFT. However, we won't be getting this from users. Since we do not allow task specific selection at run time, and use methods like average, we can just fill the task ids with 0 vector to fix this issue.
=> :bug: Fix attention mask and task_id for MPT

README.md, benchmarks/README.md, benchmarks/logs/llama2-7b/20230905_183655.output, benchmarks/logs/llama2-7b/20230905_184809.output, benchmarks/logs/llama2-7b/20230905_191650.output, benchmarks/logs/llama2-7b/20230905_194133.output, benchmarks/logs/llama2-7b/20230906_135211.output
Added a section to the main README.md for benchmarking. This links to a second README.md in ./benchmarking that contains a poorly formatted table summarizing the benchmarking results on Llama2-7b using 1 x A100 80GB. on the CCC. 
Also included under ./logs is the output from the individual benchmarks "showing our work" including **all** the parameters used for training, in the event someone wants to reproduce this.
The poor formatting on the table seems to be with how GitHub is rendering the markdown. I spent 2 hours messing with the formatting / reading docs / wasting time trying to get the column widths to adjust, but failed in every attempt. Several artifacts of this attempt are still left in the table formatting to prove that nothing works to set the column width so the table looks …
=> Added benchmarking results to main README.md

pyproject.toml
This is needed to support running caikit-nlp training jobs with Model Train using non-s3 uploads.
=> SupportCaikitZeroTwenty: Bump caikit range to allow for 0.20

caikit_nlp/toolkit/text_generation/model_run_utils.py, caikit_nlp/toolkit/text_generation/tgis_utils.py
For reproducibility purposes, the random seed used for inference should be returned to user.
=> Expose seed

caikit_nlp/resources/pretrained_model/hf_auto_causal_lm.py
This PR is a rewrite of the batch tokenization logic for causal language modeling, with the primary goal of consolidating the batch / non-batched logic, removing the duplicate code, and prioritizing readability. Doing so will make implementing chunking etc much cleaner and less error prone.
The reason this code was (originally) super ugly is that BatchEncoding objects hold batches as a dict of lists and non-batched items directly. This makes them extremely annoying to write common code for, particularly when something complicated is happening and multiple samples are being yielded per entry in the batch.
This PR adds a pre/post processing step to convert the batch encoding to a list of batch encodings, consolidates the generator func, and adds a post processing step for batching to …
=> Refactor / Consolidate Batch Tokenization for Causal Language Modeling

caikit_nlp/modules/text_classification/sequence_classification.py, caikit_nlp/modules/text_generation/peft_prompt_tuning.py, caikit_nlp/modules/text_generation/peft_tgis_remote.py, caikit_nlp/modules/text_generation/text_generation_local.py, caikit_nlp/modules/text_generation/text_generation_tgis.py, caikit_nlp/modules/token_classification/filtered_span_classification.py, caikit_nlp/modules/tokenization/regex_sentence_splitter.py, caikit_nlp/resources/pretrained_model/base.py, caikit_nlp/resources/pretrained_model/hf_auto_causal_lm.py, caikit_nlp/resources/pretrained_model/hf_auto_seq2seq_lm.py, caikit_nlp/toolkit/data_stream_wrapper.py, caikit_nlp/toolkit/data_type_utils.py, caikit_nlp/toolkit/task_specific_utils.py, caikit_nlp/toolkit/text_generation/model_run_utils.py, caikit_nlp/toolkit/text_generation/tgis_utils.py, caikit_nlp/toolkit/verbalizer_utils.py
Since `caikit` [`v0.15`](https://github.com/caikit/caikit/releases/tag/v0.15.0), `error_handler` has been moved to `caikit.core.exceptions` (from `caikit.core.toolkit.errors  error_handler`).
=> fix imports for caikit >=0.15.0

caikit_nlp/modules/text_generation/peft_prompt_tuning.py, caikit_nlp/modules/text_generation/text_generation_local.py, caikit_nlp/resources/pretrained_model/base.py, caikit_nlp/resources/pretrained_model/hf_auto_seq2seq_lm.py, caikit_nlp/toolkit/trainer_utils.py, examples/run_fine_tuning.py, tests/modules/text_generation/test_peft_prompt_tuning.py
- Update loss logging mechanism to log per step.
- NOTE: The definition of step changes depending on how the training logic is implemented and if we are using `gradient_accumulation`. In case of huggingface trainer with gradient accumulation greater than 1, the definition of step becomes when the gradients are updated, which would be at every gradient accumulation step. 
- Update prompt tuning to use step wise gradient logic
- Add utility function for trainers to use for logging 
- Extend Trainer class for both base resource and seq2seq resource to override the `log` function
- Add loss logging functionality for fine-tuning module, similar to prompt tuning.
Produces following logs in `training_logs.jsonl` for fine-tuning:
```
{"name": "loss", "data": {"epoch": 0.01, "step": 1, "value": …
```
=> Add ft loss logging

caikit_nlp/modules/text_generation/text_generation_local.py
`no_cuda` is a deprecated argument; the new arg is `use_cpu`.
=> use arg use_cpu instead of no_cuda

caikit_nlp/modules/text_generation/peft_prompt_tuning.py
closes: https://github.com/caikit/caikit-nlp/issues/218
- Add support for setting random seed for prompt tuning
=> :bug: Add support for setting random seed for prompt tuning training

caikit_nlp/modules/text_generation/peft_prompt_tuning.py, caikit_nlp/modules/text_generation/text_generation_local.py, caikit_nlp/resources/pretrained_model/hf_auto_causal_lm.py, caikit_nlp/resources/pretrained_model/hf_auto_seq2seq_lm.py, tests/resources/test_pretrained_model.py
This PR is the nth rewrite of causal language modeling tokenization, _now_ changing it to:
- Let us use sequence type tokenization with causal language models if we want to
- Or enable chunking on the concatenated sequence, optionally dropping the remainder if the chunks are uneven
Sequence type tokenization is a port of the old causal LM tokenization logic with a bug fix for the concatenation sequence length; I have verified the quality matches approximately what we would expect from prompt tuning on RTE.
Chunking seems to be functional and has tests verifying output correctness but is not publicly exposed yet and therefore has not fully quality tested.
We need to be careful about collator compatibility when changing the chunking strategy, since prompt tuning and the base model …
=> Causal LM tokenization: Chunking and seq2seq Forward

caikit_nlp/modules/text_generation/peft_prompt_tuning.py, caikit_nlp/modules/text_generation/text_generation_local.py, tests/fixtures/__init__.py, tests/modules/text_generation/test_peft_prompt_tuning.py
- Add value checks on streams in `.train` - we were seeing confusing errors on empty streams in training. Specifically, an error check on buffer size will fail when the data stream wrapper is called/used
- Update test fixtures to not have empty streams
Closes #214
=> :goal_net: Disallow empty train streams

caikit_nlp/modules/text_generation/peft_prompt_tuning.py, caikit_nlp/modules/text_generation/text_generation_local.py, tests/fixtures/__init__.py, tests/modules/text_generation/test_peft_prompt_tuning.py
Reverts caikit/caikit-nlp#223
Context: some attributes like length may not be present when attempting to create `DataStream` from `DataStreamSource`. Pending further investigation on the `caikit` side for this - we are reverting this PR to unblock
=> Revert ":goal_net: Disallow empty train streams"

examples/evaluate_model.py
Currently, the evaluation script breaks on non-prompt tuned models, because the local text generation module doesn't have a verbalizer property. This change enables the script to work on local text generation models by making the verbalized text writing conditional on whether or not a verbalizer attribute exists.
=> Make verbalizer rendering optional in eval script

.github/workflows/publish-library.yml, .gitignore, caikit_nlp/__init__.py, caikit_nlp/version.py, pyproject.toml, tox.ini
This PR changes the build system from `flit` to `setuptools`+[`setuptools_scm`](https://github.com/pypa/setuptools_scm/). The main driver behind this PR is to simplify development by having `setuptools_scm` automatically set the module version at build/install time instead of having a fixed `0.0.1` version replaced by CI.
Another advantage of using `setuptools_scm` is to have proper versions reported when using editable installs, avoiding version requirements warnings/errors.
This also adds the possibility of using `caikit_nlp.__version__`  (or `__version_tuple__`) to check  the module version at runtime
=> proposal: use setuptools/setuptools_scm for building

pyproject.toml
By not explicitly defining packages, setuptools will automatically find all packages using the flat-layout strategy.
This also prevents the following warnings to be printed when building using `python -m build`:
```
_Warning: Package 'caikit_nlp.toolkit' is absent from the `packages` configuration.
```
=> pyproject: use setuptools' automatic discovery

tox.ini
By passing `--durations`, pytest reports the longest test run times.
Here's the top 5:
```
78.01s call     tests/model_management/test_tgis_auto_finder.py::test_bad_tgis_connection
4.23s call     tests/modules/text_generation/test_text_generation_tgis.py::test_local_train_load_tgis
3.31s call     tests/modules/text_generation/test_text_generation_local.py::test_train_model_save_and_load
1.86s call     tests/modules/text_generation/test_text_generation_local.py::test_train_model_seq2seq
1.75s call     tests/modules/text_generation/test_peft_prompt_tuning.py::test_run_model
```
It's probably worth it to add a timeout to `test_bad_tgis_connection` to avoid spending so much time there.
=> tox: run pytest with --durations flag to list tests run time

caikit_nlp/config/config.yml, caikit_nlp/modules/text_generation/peft_prompt_tuning.py, pyproject.toml, tests/modules/text_generation/test_peft_prompt_tuning.py
- Add training data limit which should be configurable by module and model
=> Add data limitation

caikit_nlp/toolkit/text_generation/model_run_utils.py, tests/toolkit/text_generation/test_model_run_utils.py
=> fix uncaught exception in http client

tests/fixtures/__init__.py, tests/modules/text_generation/test_peft_prompt_tuning.py
Slightly improve tests times by marking some expensive fixtures as session scoped
=> tests: make models fixtures session-scoped

caikit_nlp/modules/text_generation/peft_prompt_tuning.py, caikit_nlp/modules/text_generation/text_generation_local.py, caikit_nlp/toolkit/text_generation/model_run_utils.py, tests/modules/text_generation/test_peft_prompt_tuning.py, tests/modules/text_generation/test_text_generation_local.py, tests/toolkit/text_generation/test_model_run_utils.py
for: https://github.com/caikit/caikit-nlp/issues/243
adds a flag to preserve or remove input text from output of CAUSAL models (**local inferencing** of prompt tuning and generation)
this will achieve functional parity with TGIS
The change will enable local evaluation of causal models without TGIS
=> Add preserve input text inference

caikit_nlp/modules/text_embedding/embedding.py, tests/modules/text_embedding/test_embedding.py
Add flag to use pytorch compile and/or try IPEX.
To use IPEX:
1.  Install intel-extension-for-pytorch
2. Set env var USE_IPEX=true
Default is false.  If set to true, but the import fails, then a warning will be logged and USE_IPEX will be disabled.
Optionally, USE_XPU may be set to true to allow IPEX to use its xpu (only applies when IPEX is active).
USE_MPS has been added for GPU testing on Macbook (ignored when IPEX is used).
To invoke torch.compile() optimization, set the env var PT2_COMPILE=true.
torch.compile() is not available on all versions/platforms.  A warning message is logged if this is enabled and throws an exception.
=> Text Embedding: Add optimizations with PT2_COMPILE and/or IPEX

caikit_nlp/toolkit/trainer_utils.py
For user understandability include the actual and max training sizes in the error message.
Based on release.0.3 branch.
=> Add max size information to error message [release-0.3]

caikit_nlp/modules/text_embedding/embedding.py, tests/modules/text_embedding/test_embedding.py
The desired functionality here is that a request which would be truncated (to work with a model max_seq_len) should instead return an error message.  The reasoning is that the client would want to know, instead of just getting results without realizing the impact of truncation.
In order to consider the token truncation (not string truncation), this requires tokenization up front and avoiding a warning about parallelism on the first attempt.
To be consistent with the user experience with other models, the default will throw an error with the models max_seq_len is exceeded (this is not the sentence-transformers default behavior so it is implemented here).  In addition, here we add the optional truncate_input_tokens parameter.  This is consistent with other services, and in addition to …
=> Text Embedding: Truncation allow or fail with optional parameter

caikit_nlp/modules/text_embedding/embedding.py, tests/modules/text_embedding/test_embedding.py
The use of tokenizer for truncation before using the sentence-transformers model to encode hits "Already borrowed" errors because the fast tokenizer (Rust) isn't very Python thread-friendly.
* Add retry to fix the problem and future problems
* A simple retry loop usually fixes the problem immediately
* Use a little sleep that increases
* Add RETRY_COUNT so the max can be changed if needed
* Use a separate tokenizer instance for truncate
* Using a separate copy of the tokenizer avoids the concurrency problem as reproduced so far
* Don't use decode()
* Less use of tokenizer should help with above issues
* This makes the truncated string more exactly as it should be.  With decode() is was an inexact reproduction inconsistent with non-truncated text handling.
* Add BATCH_SIZE env var to allow …
=> Text Embedding: Fix concurrency errors

pyproject.toml
=> deps: update peft to install from pypi

Dockerfile
=> bump dockerfile ubi base

caikit_nlp/modules/token_classification/filtered_span_classification.py, tests/modules/token_classification/test_filtered_span_classification.py
Return empty classification results when classification is invoked with empty text or empty text stream. This would prevent potential further errors that _may_ incur if any models used (tokenizers or classifiers cannot handle empty strings properly). Empty text _could_ have been considered an error but based on current usage this would not be a desired user experience
=> :goal_net: Handle empty text for filtered span classification

.pre-commit-config.yaml, caikit_nlp/resources/pretrained_model/base.py
- Pull changes to main: https://github.com/caikit/caikit-nlp/pull/308
=> :loud_sound: Add model and tokenizer time logging

caikit_nlp/modules/text_generation/peft_prompt_tuning.py, caikit_nlp/resources/pretrained_model/hf_auto_causal_lm.py, caikit_nlp/toolkit/text_generation/granite_modeling_llama.py, pyproject.toml
- Update peft to make it work with llama models. This PR will take care of https://github.com/caikit/caikit-nlp/pull/305
- Update transformers library to make it work with new caching module required by llama models
- Add `granite_modeling_llama` module that declares, defines and registers new transformers model type (`gpt_megatron`) into transformers causal lm registry thus allowing us to load sphinx / granite models with `AutoModelForCausalLM` and prompt tune those.
- Integrate `granite_modeling_llama` script into causal-lm resource.
- Fix bug to provide safe deletion of model config attribute
- Fix bug to use `torch_dtype` at load time for prompt tuning local inferencing
=> :package: Update transformers to min of 4.36.0 to get new caching module

caikit_nlp/modules/text_embedding/embedding.py, tests/modules/text_embedding/test_embedding.py
The retry (which was added to mitigate thread contention "already borrowed" errors) had some undesirable behavior. It was hiding the actual error. Also, now that we got that original problem fixed, this generally should be turned off so we won't eat-and-repeat on real errors.
* Default to no retries
* Capture the original exception and raise that if retries don't succeed (log the retries)
* Make it more testable and test the exception handling better.
Fixes #315
=> Embeddings: Fix retry error handling to return first exception. Default to zero retries.

caikit_nlp/modules/text_embedding/embedding.py
Add an earlier model.eval() since embeddings models are always used for inference.
Fixes #317
=> Embeddings: IPEX optimize requires model.eval() called first.

pyproject.toml, sentence-transformers.nodeps.txt, tox.ini
Need to make sentence-transformers part of the default caikit-nlp runtime image. Previously this was an optional import requiring a special runtime image.
* Make sentence-transformers one of the dependencies
* Remove the just-for-testing no-deps support that was a work-around
=> Add sentence-transformers to dependencies for real

caikit_nlp/modules/text_generation/peft_tgis_remote.py, caikit_nlp/modules/text_generation/text_generation_tgis.py, caikit_nlp/toolkit/text_generation/tgis_utils.py, pyproject.toml, tests/fixtures/__init__.py, tests/modules/text_generation/test_peft_tgis_remote.py, tests/modules/text_generation/test_text_generation_tgis.py
Added tokenization tasks in order to serve tokenization request and return the token count
=> added tokenization tasks to serve tokenization requests

caikit_nlp/modules/text_embedding/embedding.py, pyproject.toml, tests/modules/text_embedding/test_embedding.py
Depends on caikit data model updates in this PR: https://github.com/caikit/caikit/pull/675
This extends the embedding module to include the `input_token_count` in the results of the `EmbeddingModule`'s `run_` methods.
The `sum_token_count(tokenized: BatchEncoding) -> int` function calculates the count of tokens requiring model attention, based on the `Encoding.attention_mask` property, as returned by `SentenceTransformerWithTruncate.tokenizer()`. [PAD] is irrelevant for truncation and max_token_count parameters, while [CLS] and [SEP] are counted by the model when it considers the max length and truncation.
Additionally tests to confirm sort order is maintained was added.
Various other quality of life type hints were added.
=> Include input token count in results

caikit_nlp/modules/__init__.py, caikit_nlp/modules/token_classification/filtered_span_classification.py
Functionality tested through `test_bootstrap_run_empty`
=> :zap: Tee stream instead of checking length

caikit_nlp/modules/text_embedding/embedding.py, tests/modules/text_embedding/test_embedding.py
* Attempting truncate_input_tokens=2 (or 1) was creating a strange error (or misbehaving) because it takes at least 3 tokens for [CLS] TOK [SEP] for meaningful results.
* Now that truncate value generally means number of tokens not including begin/end.
* On the max end the 2 special tokens will be allowed to consume 2 from the limit.
* Batch embedding processing was returning odd/misordered results when combined with truncation. Added a re tokenize() call to avoid sending the overflow tokens as features to be processed.
=> Embeddings fix for truncation without room for begin/end and for batch truncation

tests/modules/text_embedding/test_embedding.py
* Test for 2 identical strings to return identical vectors
* Also tests that batch vs single/loop are approx same
* This test would have found a bug that was recently fixed
=> Embedding add a test that would have helped

caikit_nlp/modules/text_generation/peft_prompt_tuning.py, caikit_nlp/modules/text_generation/text_generation_local.py, caikit_nlp/toolkit/torch_run.py, pyproject.toml, tests/modules/text_generation/test_peft_prompt_tuning.py, tests/modules/text_generation/test_text_generation_local.py
Closes https://github.com/caikit/caikit-nlp/issues/350
Because `TextGenerationTGIS` is not a subclass but a backend type for `TextGeneration`, any additional tasks declared on the former were not actually getting added. By adding the additional tasks on `TextGeneration` and `PeftPromptTuning` respectively, this allows the tokenization tasks to be available on the TGIS backend implementations. Unimplemented functions have to be added or there will be errors.
Tokenization run functions could eventually be implemented since each LLM could be reasonably expected to have a tokenizer.
`Std` getting imported with `LaunchConfig` started to error in latest torch `2.3.0`. It was observed the `Std` object is at https://github.com/pytorch/pytorch/blame/main/torch/distributed/elastic/multiprocessing/ap …
=> :sparkles: Add tokenization task to generation modules

Dockerfile, pyproject.toml
image builds are currently taking 5+h and failing because of pip backtracking.
- deps: pin grpc-\* to a recent version to avoid pip backtracking
- Dockerfile: create venv with updated pip/setuptools
=> prevent pip backtracking

caikit_nlp/config/config.yml, caikit_nlp/toolkit/text_generation/tgis_utils.py, tests/fixtures/__init__.py, tests/toolkit/text_generation/test_tgis_utils.py
- Add configurable request timeout for request going to TGIS backend
=> Add tgis timeout

caikit_nlp/modules/text_embedding/embedding.py, pyproject.toml, tests/modules/text_embedding/test_embedding.py
- Expose model information for embeddings service (`max_seq_lenght` +`sentence_embedding_dimension`) 
**Depends on**: https://github.com/caikit/caikit/pull/723
=> Expose model information for embeddings service

caikit_nlp/toolkit/text_generation/tgis_utils.py
This PR adds logging to the tgis_req_timeout config setting, to add debug log surrounding this configuration and ensure proper setting.
=> logging around tgis timout config setting

caikit_nlp/modules/text_generation/peft_tgis_remote.py, caikit_nlp/modules/text_generation/text_generation_tgis.py, caikit_nlp/toolkit/text_generation/tgis_utils.py, pyproject.toml, tests/fixtures/__init__.py, tests/modules/text_generation/test_text_generation_tgis.py, tests/toolkit/text_generation/test_tgis_utils.py
This PR adds support for respecting a TGIS hostname override (`x-route-info` header/metadata).
This is achieved by lazily registering the model connection with the TGISBackend when `.run()`/`run_stream_out()`/`run_tokenizer()` is called. The `x-route-info` header/metadata is read from the context arg.
Additionally:
- a `TextGenerationTGIS._tgis_backend` property was added to be consistent with `PeftPromptTuningTGIS`. The `TextGenerationTGIS.tgis_backend` property is conditional on the `tgis_backend` argument to be True, which made accessing `TextGenerationTGIS.tgis_backend` risky as it might not exist. The additional `_tgis_backend` property is guaranteed to exist, making using it simpler and less risky.
Depends on `caikit-tgis-backend>=0.1.33`
=> Lazy model connection & x-route-info

caikit_nlp/modules/text_generation/peft_tgis_remote.py, caikit_nlp/modules/text_generation/text_generation_tgis.py, caikit_nlp/toolkit/text_generation/tgis_utils.py, pyproject.toml, tests/toolkit/text_generation/test_tgis_utils.py
The `include_stop_sequence` option is provided by tgis, which the user can set to include the STOP_SEQUENCE in the output.
This PR makes the option available in the FastAPI endpoint
=> Add param include_stop_sequence

caikit_nlp/toolkit/torch_run.py, pyproject.toml, tests/modules/text_embedding/test_embedding.py
- Update pytorch to 2.3.1 to address CVE
=> :package: Update torch to 2.3.1

caikit_nlp/toolkit/text_generation/tgis_utils.py
- Catch grpc `InactiveError` and through more helpful error message.
=> :goal_net: Catch InactiveError for TGIS to modify error message

.github/workflows/build-image.yml
We've seen multiple PR build failures on the image build workflow with `buildx failed with: ERROR: failed to solve: rpc error: code = Unknown desc = write /opt/caikit/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so: no space left on device`
=> :construction_worker: Reclaim space on image build

caikit_nlp/toolkit/text_generation/tgis_utils.py
Previously #372 was added to give connection errors a more understandable user message, but this obscured some unary generation validation errors
In this PR:
- Serializing `err.details` was leading to JSON errors - this should be `err.details()`
- Non-connection errors such as validation errors [invalid argument] were getting surfaced with the inactive RPC connection message incorrectly
Test command with this fix
```
grpcurl -plaintext -H "mm-model-id: [model-id]" -d '{
"stopSequences": [],
"text": "sad",
"tokenLogprobs": true
}' localhost:8085 caikit.runtime.Nlp.NlpService.TextGenerationTaskPredict
```
=> :goal_net: Handle error details on inactive rpc errors

caikit_nlp/modules/text_embedding/embedding.py, tests/modules/text_embedding/test_embedding.py
Allows users to pass tokenizer keyword argument to select the tokenizer settings desired. In this case, enabling for pad_to_max_length.
=> Enable using kwargs for selecting pad-to-max-length strategy for tokenizer in embeddings
