caikit_nlp/modules/text_generation/peft_tgis_remote.py
caikit_nlp/modules/text_generation/text_generation.py

- Add `max new tokens` and `min new tokens` param for text generation with TGIS backend

Support tgis stop params

---

.github/workflows/publish-library.yml
tox.ini

Add github workflow to publish to pypi so that other projects could pull this in as a dependency

:construction_worker: Add publish to pypi

---

caikit_nlp/modules/token_classification/filtered_span_classification.py
tests/modules/token_classification/test_filtered_span_classification.py

- Fix case where input text stream contains chunked texts. 
Closes #61

:bug: Fix streaming of chunked texts

---

caikit_nlp/modules/token_classification/filtered_span_classification.py
tests/modules/token_classification/test_filtered_span_classification.py

- Fix issue where if a sentence in the middle of the stream has trailing or leading whitespaces, then the offsets would be off and we may miss processing 1 character (start of the sentence for next sentence)

:bug: Fix issues with stream-span processing with trailing or leading whitespaces

---

caikit_nlp/modules/text_generation/__init__.py
caikit_nlp/modules/text_generation/fine_tuning.py
caikit_nlp/toolkit/data_stream_wrapper.py
examples/run_fine_tuning.py
examples/run_peft_tuning.py
tests/fixtures/__init__.py
tests/modules/text_generation/test_fine_tuning.py
tests/toolkit/test_data_stream_wrapper.py

closes: #71 
- Add fine-tuning module that uses HF Trainer to showcase how we can use it to fine-tune a model.
- This is purposefully only using 1 type of trainer and supporting 1 type of models. The purpose is to lay out small changes and iteratively improve to avoid giant PRs.
- For this PR to work fully, we need to update `transformers` version to include the bugfix merged in the PR https://github.com/huggingface/transformers/pull/24759

Add finetuning generation

---

caikit_nlp/config/config.yml
caikit_nlp/data_model/generation.py
caikit_nlp/modules/text_generation/fine_tuning.py
caikit_nlp/modules/text_generation/peft_prompt_tuning.py
caikit_nlp/modules/text_generation/peft_tgis_remote.py
caikit_nlp/modules/text_generation/text_generation.py
caikit_nlp/modules/text_generation/text_generation_task.py
tests/data_model/test_generated_result.py
tests/fixtures/data_model/sample_objects.py
tests/modules/text_generation/test_fine_tuning.py
tests/modules/text_generation/test_peft_prompt_tuning.py

Reference: https://github.com/caikit/caikit/blob/main/caikit/interfaces/nlp/data_model/text_generation.py

:recycle: Use generated text result from caikit.interfaces

---

examples/utils.py

- fix backends configuration for example scripts to supported caikit updated API

:wrench: Fix utils script to configure backends in the new way in updated caikit

---

caikit_nlp/modules/text_generation/peft_prompt_tuning.py

:fire: Remove print in module code

---

README.md

This README update includes 
1. links to other resources around caikit land
1. Information from slack about things - not taking credit, all I did was some grammar checking
1. boiler plate one would normally expect to see in a top level readme.me

[NO-JIRA] Update README.md

---

caikit_nlp/modules/text_generation/peft_prompt_tuning.py

This audits the peft module and adds logs to the value checks that didn't have them

:loud_sound: add value check logs

---

caikit_nlp/modules/text_generation/peft_prompt_tuning.py
caikit_nlp/modules/text_generation/text_generation_local.py
caikit_nlp/toolkit/text_generation/model_run_utils.py
tests/modules/text_generation/test_peft_prompt_tuning.py

:sparkles: Add support for additional generate params

---

caikit_nlp/modules/text_generation/peft_prompt_tuning.py
caikit_nlp/modules/text_generation/peft_tgis_remote.py
caikit_nlp/modules/text_generation/text_generation_tgis.py
caikit_nlp/toolkit/text_generation/model_run_utils.py

🐛 stop_sequences as list of str

---

CODEOWNERS

Add Thara as maintainer of caikit-nlp

Add Thara as maintainer 🥳 

---

caikit_nlp/config/config.yml
caikit_nlp/modules/text_generation/peft_prompt_tuning.py
caikit_nlp/modules/text_generation/text_generation_local.py
caikit_nlp/resources/pretrained_model/base.py
caikit_nlp/resources/pretrained_model/hf_auto_causal_lm.py
caikit_nlp/resources/pretrained_model/hf_auto_seq2seq_lm.py
caikit_nlp/resources/pretrained_model/hf_auto_seq_classifier.py
caikit_nlp/toolkit/torch_run.py
examples/run_fine_tuning.py
pyproject.toml
tests/modules/text_generation/test_text_generation_tgis.py
tests/resources/test_pretrained_model.py

Giant PR encapsulating most of the work @gkumbhat and I have done towards enabling fully sharded data parallel / multi GPU for fine-tuning large language models 😬

Experiment sharding rebase

---

examples/evaluate_model.py

- Fix eval script model.run call

:bug: Fix eval script for updated run datamodel

---

caikit_nlp/modules/text_generation/peft_prompt_tuning.py
tests/modules/text_generation/test_peft_prompt_tuning.py

Supports: #179 
- Add loss logging for prompt-tuning

Add loss logging prompt-tuning

---

examples/evaluate_model.py

- update arg for `metric` to use `choices` param to check the arg passed
- remove manual check for arg passed
- fix `metric_funcs` to be based on arg

fix: use cli args for metrics to run

---

caikit_nlp/modules/text_generation/peft_config.py
caikit_nlp/modules/text_generation/peft_prompt_tuning.py
tests/modules/text_generation/test_peft_config.py

Rebased version of @rawkintrevo's PR https://github.com/caikit/caikit-nlp/pull/174 with some minor changes to tests and the error handler.

[caikit-nlp-163] Refactor peft module to take out common peft config functionality

---

caikit_nlp/modules/text_generation/peft_tgis_remote.py
caikit_nlp/modules/text_generation/text_generation_tgis.py

Align inference parameter ordering for all text generation modules

🐛 Align inference params order

---

caikit_nlp/resources/pretrained_model/base.py
tests/resources/test_pretrained_model.py

- Fix tokenization via model path issue

Fix tokenization path

---

caikit_nlp/modules/text_generation/peft_prompt_tuning.py
caikit_nlp/modules/text_generation/peft_tgis_remote.py
caikit_nlp/modules/text_generation/text_generation_local.py
caikit_nlp/modules/text_generation/text_generation_tgis.py

- Update docstring formatting function

:technologist: Fix docstring formatting function call

---

caikit_nlp/modules/text_generation/peft_prompt_tuning.py
caikit_nlp/toolkit/text_generation/model_run_utils.py
caikit_nlp/toolkit/text_generation/tgis_utils.py
pyproject.toml

fix pylint warnings

---

caikit_nlp/modules/text_generation/peft_prompt_tuning.py
caikit_nlp/modules/text_generation/peft_tgis_remote.py
caikit_nlp/modules/text_generation/text_generation_tgis.py
caikit_nlp/toolkit/text_generation/model_run_utils.py

- Fix sequencing of arguments on run function as that can create weird runtime argument mismatch issue

:ambulance::wrench: Fix sequencing of arguments on run function

---

caikit_nlp/modules/text_generation/peft_prompt_tuning.py

- Change how we fetch the float value from loss tensor to avoid potentially weird memory issues
Ref blog talking about this: https://medium.com/@raghadalghonaim/memory-leakage-with-pytorch-23f15203faa4

:bug: Fix loss tensor to float conversion

---

.dockerignore
.github/workflows/build-image.yml
Dockerfile
README.md

- Add a `Dockerfile` definition: this copies the built wheel into the container and installs it
- Add a github actions workflow to build the dockerfile

Add dockerfile

---

.github/workflows/build-image.yml
.github/workflows/build-library.yml
.github/workflows/lint-code.yml

- Add branch pattern for release branches

:construction_worker: Update github action workflow rule for release branches

---

caikit_nlp/modules/text_generation/peft_tgis_remote.py
pyproject.toml
tests/modules/text_generation/test_peft_tgis_remote.py

See https://github.com/caikit/caikit-tgis-backend/pull/45
(And don't merge before that + a tgis backend release is cut)

:bug: fix tgis backend purge

---

CODEOWNERS

Add Sukriti

---

caikit_nlp/toolkit/trainer_utils.py

Ref: #279 
Pull in changes from 0.3 release to main branch

Add max size information to error message

---

caikit_nlp/modules/text_generation/peft_tgis_remote.py
pyproject.toml
tests/modules/text_generation/test_peft_tgis_remote.py

See https://github.com/caikit/caikit-nlp/pull/282

Fix prompt unload (main)

---

.github/workflows/publish-library.yml

Similar fixes as https://github.com/caikit/caikit/pull/549 and https://github.com/caikit/caikit-tgis-backend/pull/41 to enable publishing

:bug: Tox install

---

caikit_nlp/modules/token_classification/filtered_span_classification.py
tests/modules/token_classification/test_filtered_span_classification.py

Duplicate of #304 but off the 0.3 release branch

🥅 Handle empty text for filtered span classification [0.3 release]

---

.pre-commit-config.yaml
caikit_nlp/resources/pretrained_model/base.py

- Add `platformdirs` for formatter to avoid errors on mac for `black`
- Add time based context logging for tokenizer and model loading for base models. This will allow us to get better picture of training time.

Add model load logging

---

caikit_nlp/modules/text_generation/peft_tgis_remote.py
caikit_nlp/modules/text_generation/text_generation_tgis.py
caikit_nlp/toolkit/text_generation/tgis_utils.py
pyproject.toml
tests/fixtures/__init__.py
tests/modules/text_generation/test_peft_tgis_remote.py
tests/modules/text_generation/test_text_generation_tgis.py

[duplicate PR of 325](https://github.com/caikit/caikit-nlp/pull/325) , which Added tokenization tasks in order to serve tokenization request and return the token count

duplicate PR for tokenization tasks request

---

caikit_nlp/modules/token_classification/filtered_span_classification.py
tests/modules/token_classification/test_filtered_span_classification.py

Add more flexibility to thresholds

:goal_net: Allow int thresholds [release-0.3]

---

caikit_nlp/modules/text_generation/peft_tgis_remote.py
caikit_nlp/modules/text_generation/text_generation_tgis.py
caikit_nlp/toolkit/text_generation/tgis_utils.py
pyproject.toml
tests/toolkit/text_generation/test_tgis_utils.py

Forward get_route_info and ROUTE_INFO_HEADER_KEY from backend

---

pyproject.toml

Update floor value of torch version to 2.2.2 so fix CVE
https://nvd.nist.gov/vuln/detail/CVE-2024-5480

Fix CVE-2024-5480
